# Generated by Django 6.0.1 on 2026-01-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='accounts.profile'),
        ),
    ]
