# Generated by Django 6.0.1 on 2026-01-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='viewed_profiles',
            field=models.ManyToManyField(blank=True, related_name='viewed_by', to='accounts.profile'),
        ),
    ]
