# Generated by Django 6.0.1 on 2026-01-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_completed',
        ),
    ]
